
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankAccountService", targetNamespace = "http://ws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankAccountService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionEuroToDh", targetNamespace = "http://ws.com/", className = "proxy.ConversionEuroToDh")
    @ResponseWrapper(localName = "conversionEuroToDhResponse", targetNamespace = "http://ws.com/", className = "proxy.ConversionEuroToDhResponse")
    @Action(input = "http://ws.com/BankAccountService/conversionEuroToDhRequest", output = "http://ws.com/BankAccountService/conversionEuroToDhResponse")
    public double conversionEuroToDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://ws.com/", className = "proxy.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://ws.com/", className = "proxy.GetAccountResponse")
    @Action(input = "http://ws.com/BankAccountService/getAccountRequest", output = "http://ws.com/BankAccountService/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccounts", targetNamespace = "http://ws.com/", className = "proxy.GetAccounts")
    @ResponseWrapper(localName = "getAccountsResponse", targetNamespace = "http://ws.com/", className = "proxy.GetAccountsResponse")
    @Action(input = "http://ws.com/BankAccountService/getAccountsRequest", output = "http://ws.com/BankAccountService/getAccountsResponse")
    public List<Account> getAccounts();

}
